markdown: rdiscount
permalink: /:title/
url: http://hustcat.github.io
name: YY哥
author: hustcat
qq: 
email: hustcat@gmail.com
duoshuo: hustcat
beian: 
cnzz: 
weibo: hustcat
github: hustcat
pygments: true
safe: true
paginate: 20
about: "YY哥(hustcat)"
